spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sql6474577
    url: jdbc:mysql://sql6.freemysqlhosting.net/sql6474577
    password: EQQIRVvnty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
